services:
  db:
    image: mysql:8.0
    container_name: dota2_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dota2_net

  app:
    build: .
    container_name: dota2_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Внутри Docker-сети MySQL доступен по имени сервиса "db"
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "80:5000"
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dota2_net

  collector:
    build: .
    container_name: dota2_collector
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
    command: python collector_scheduler.py
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - dota2_net

volumes:
  mysql_data:

networks:
  dota2_net:
    driver: bridge